enum Energy {
  NEUTRAL = 'NEUTRAL',
  PLANT = 'PLANT',
  FIRE = 'FIRE',
  WATER = 'WATER',
  LIGHTNING = 'LIGHTNING',
  FIGHTING = 'FIGHTING',
  PSYCHIC = 'PSYCHIC',
  DARKNESS = 'DARKNESS',
  METAL = 'METAL',
  DRAGON = 'DRAGON',
  FAIRY = 'FAIRY'
}

export default Energy;